#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o pipefail

repo_root="$(readlink -f $(dirname ${0})/..)"

export KUBECONFIG=$repo_root/gardener/dev-setup/gardenlet/components/kubeconfigs/seed-local/kubeconfig

echo "Generating ${repo_root}/dev/extension/kustomization.yaml"
mkdir -p ${repo_root}/dev/extension

cat  << EOF > ${repo_root}/dev/extension/kustomization.yaml
# DO NOT EDIT THIS FILE!
# This file is auto-generated by hack/prepare-extension-up.sh.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../example/extension/base

patches:
- path: extension-patch.yaml
  target:
    group: operator.gardener.cloud
    kind: Extension
    name: extension-dummy-service
EOF

echo "Generating ${repo_root}/dev/extension/extension-patch.yaml"

cat  << EOF > ${repo_root}/dev/extension/extension-patch.yaml
# DO NOT EDIT THIS FILE!
# This file is auto-generated by hack/prepare-extension-up.sh.

apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: extension-dummy-service
spec:
  deployment:
    extension:
      helm:
        ociRepository:
          ref: local-skaffold/gardener-extension-dummy-service/charts/extension:v0.0.0
      values:
        bar: skaffold-bar
EOF
