//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	service "github.com/MartinWeindel/gardener-extension-dummy-service/pkg/apis/service"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*DummyConfig)(nil), (*service.DummyConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DummyConfig_To_service_DummyConfig(a.(*DummyConfig), b.(*service.DummyConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*service.DummyConfig)(nil), (*DummyConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_service_DummyConfig_To_v1alpha1_DummyConfig(a.(*service.DummyConfig), b.(*DummyConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_DummyConfig_To_service_DummyConfig(in *DummyConfig, out *service.DummyConfig, s conversion.Scope) error {
	out.Foo = (*string)(unsafe.Pointer(in.Foo))
	return nil
}

// Convert_v1alpha1_DummyConfig_To_service_DummyConfig is an autogenerated conversion function.
func Convert_v1alpha1_DummyConfig_To_service_DummyConfig(in *DummyConfig, out *service.DummyConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_DummyConfig_To_service_DummyConfig(in, out, s)
}

func autoConvert_service_DummyConfig_To_v1alpha1_DummyConfig(in *service.DummyConfig, out *DummyConfig, s conversion.Scope) error {
	out.Foo = (*string)(unsafe.Pointer(in.Foo))
	return nil
}

// Convert_service_DummyConfig_To_v1alpha1_DummyConfig is an autogenerated conversion function.
func Convert_service_DummyConfig_To_v1alpha1_DummyConfig(in *service.DummyConfig, out *DummyConfig, s conversion.Scope) error {
	return autoConvert_service_DummyConfig_To_v1alpha1_DummyConfig(in, out, s)
}
